### ISSUE TITLE
Hacktoberfest 2023 🎉 :  Update the social media links

### ISSUE THREAD

**Issue by VidhiBhatt01** [Codess-Cafe/Codess-Website#11]
Update the social media links. Correct links are as attached in the footer of the website

![image](https://github.com/Codess-Cafe/Codess-Website/assets/83345228/4e93a55d-87c4-43b8-9cbe-8e0a21a8d074)

**Comment by AlexVCS** [comment]
I'd like to work on this issue. Can you assign it to me please?

**Comment by op-amateur** [comment]
Can you please assign me this issue? I would like to work on it under Hacktoberfest23, thank you.

**Comment by VidhiBhatt01** [comment]
@op-amateur, this issue is resolved by Alex. Please checkout the other issues on the repo. Thanks!

**Comment by Ruchip16** [comment]
closing the issue as PR has been merged
