### ISSUE TITLE
Hacktoberfest 2023 🎉 :  Enhance the Alignment of Chapter Cards

### ISSUE THREAD

**Issue by VidhiBhatt01** [Codess-Cafe/Codess-Website#12]
Fix the cards. 

[1] The current card alignment does not look visually appealing as there are 7 cards. Either realign them in format of 4 and 3 or completely redesign them.
[2]  Update the name in India Chapter. Program led by Vidhi Bhatt

![image](https://github.com/Codess-Cafe/Codess-Website/assets/83345228/623d3ff9-ee75-4d21-8ae7-0cd13d7492eb)

**Comment by Parthasarathip123** [comment]
i would like to work on this issue can you assign me this @VidhiBhatt01

**Comment by Reene-Simon** [comment]
@VidhiBhatt01 could u please assign this issue to me? I would love to work on this issue as one of my first issues.

**Comment by VidhiBhatt01** [comment]
@Reene-Simon, you may raise a PR for this too. Will consider whosoever out of you two raises a valid PR first

**Comment by Reene-Simon** [comment]
@VidhiBhatt01 in the cloned version that I have the last card i.e. the UAE chapter isn't there. Is it an issue on my end? What can I do about it?

**Comment by geetika005** [comment]
I would like to work on this issue if its still open

**Comment by VidhiBhatt01** [comment]
> @VidhiBhatt01 in the cloned version of the repo that I have the last card i.e. the UAE chapter isn't there. Is it an issue on my end? What can I do about it?
> 
> Or should I just copy the add the relevant code to my version and make the PR with the required changes?

Delete repo on local and clone again

**Comment by Reene-Simon** [comment]
![Codess Main Branch](https://github.com/Codess-Cafe/Codess-Website/assets/112744886/e937b789-a06f-4d03-b147-681f81052939)
@VidhiBhatt01 this is the image of the main branch that is there on GitHub. The last card i.e. the UAE chapter isn't there in this too. According to your suggestion I even cloned it again after syncing the fork but its not showing the same.  What should I do?

**Comment by VidhiBhatt01** [comment]
<div class="slide-container col-md-4">
          <div class="slide-card">
                <img height="180px" width="100%" src="https://www.airpano.ru/files/dubai-uae/images/image1.jpg">
                <h5>United Arab Emirates Chapter</h5>
                <h6>Program led by Yashaswini Shivathaya<br><br></h6>
          </div>
</div>

Use this
