### ISSUE TITLE
Hacktoberfest 2023 🎉 :  Remove the cards, Update the Footer

### ISSUE THREAD

**Issue by VidhiBhatt01** [Codess-Cafe/Codess-Website#13]
Remove these 2 cards.

![image](https://github.com/Codess-Cafe/Codess-Website/assets/83345228/4788e0cb-de32-4577-8c89-618a4fabc070)

Update the footer

Change 2022 -> 2023

![image](https://github.com/Codess-Cafe/Codess-Website/assets/83345228/2e1ae073-e62c-4211-82e4-33d4028603e4)

**Comment by Anemaygi** [comment]
Hi, can you assign this issue to me? Thank you!

**Comment by Parthasarathip123** [comment]
can you assign me this work @VidhiBhatt01

**Comment by joeyouss** [comment]
@Parthasarathip123 , since @Anemaygi already commented on the issue and made a PR - would it be okay if you take a look on some other issue to work on?

**Comment by Parthasarathip123** [comment]
okay thank you
