### ISSUE TITLE
Hacktoberfest 2023 🎉 : Beautify the Readme section of the repo

### ISSUE THREAD

**Issue by VidhiBhatt01** [Codess-Cafe/Codess-Website#15]
Few ideas : Add good OSS contribution guidelines, Codess Cafe logo, guidelines to setup project on local, helpful commands, etc..

**Comment by Parthasarathip123** [comment]
can you assign me this work @VidhiBhatt01

**Comment by prernamittal** [comment]
Hello, I would like to work on this issue! @VidhiBhatt01

**Comment by VidhiBhatt01** [comment]
Assigning @prernamittal as you already have one issue assigned @Parthasarathip123

**Comment by prernamittal** [comment]
@VidhiBhatt01 Should I make a separate contribution guidelines file as per the standard or include it in the main readme only?

**Comment by Ruchip16** [comment]
closing this issue as the PR is merged
