### ISSUE TITLE
Updation of twitter icon

### ISSUE THREAD

**Issue by vinay-s36** [Codess-Cafe/Codess-Website#20]
Twitter icon is not yet updated 

![Screenshot 2023-10-15 202931](https://github.com/Codess-Cafe/Codess-Website/assets/124019116/7723515c-60ab-4c40-97e8-00b915b9b36a)

**Comment by Reene-Simon** [comment]
@joeyouss and @VidhiBhatt01 Could u please assign me this issue? I would love to work on it as my very first issue.

**Comment by VidhiBhatt01** [comment]
@vinay-s36 in which PR is this issue completed?

**Comment by VidhiBhatt01** [comment]
@vinay-s36, assigned it to you. Please complete it soon..

**Comment by vinay-s36** [comment]
hey @VidhiBhatt01 since twitter's icon X is new there's no proper icon to match the style of other existing social media icons

The best one i got is this
![Screenshot 2023-10-17 234945](https://github.com/Codess-Cafe/Codess-Website/assets/124019116/7a4830de-7b7f-4003-9049-635650586f04)

If you are okay with it i will change in other pages also and give PR

**Comment by VidhiBhatt01** [comment]
I have an idea to keep it uniform.

Use canva -> get the hex code of the purple color used in other logos ->
set it as background color -> add new X logo -> use this newly created logo image for the PR

**Comment by VidhiBhatt01** [comment]
Medium and youtube logos are also bot aligned perfectly in the circle I feel. Fix it similarly as well if possible

**Comment by vinay-s36** [comment]
Hii @VidhiBhatt01 i have updated Medium and Youtube icons properly in home page but i was not able to make new twitter icon same as other icons

![Screenshot 2023-10-18 102238](https://github.com/Codess-Cafe/Codess-Website/assets/124019116/128b042a-b660-4ba9-8f9d-382b3d9af2da)


I can give PR for updation of medium and yt icons or u can unassign me for this issue
Thank you
