### ISSUE TITLE
Space b/w iamge and details is missing

### ISSUE THREAD

**Issue by Tooba-Amjad** [Codess-Cafe/Codess-Website#21]
There must be an accurate space b/w the image and name of **Jyoti Bisht** & **Yashaswini Shivathaya**

![Screenshot (191)](https://github.com/Codess-Cafe/Codess-Website/assets/106931048/d895f7f5-2a81-4b4c-822a-65cee8a3e973)

![Screenshot (190)](https://github.com/Codess-Cafe/Codess-Website/assets/106931048/b1270923-172e-43f2-a3f8-470c3aeae315)

**Add this issue under hacktoberfest**

**Comment by AmanB-2003** [comment]
Please assign this issue to me

**Comment by VidhiBhatt01** [comment]
Would assign if the issue still persists after #2 and #4 are resolved

**Comment by VidhiBhatt01** [comment]
@Tooba-Amjad, I have assigned you #2. You may fix it in the same PR( the one you will raise while resolving #2)

> Would assign if the issue still persists after #2 and #4 are resolved
