### ISSUE TITLE
smooth-scrolling

### ISSUE THREAD

**Issue by VinayBagalakoti** [Codess-Cafe/Codess-Website#22]
I can make the scrolling smooth and add mouse pointer follower effect

**Comment by VidhiBhatt01** [comment]
Any photos/videos for the mouse pointer effect?

**Comment by VinayBagalakoti** [comment]
https://vinaybagalakoti.github.io/anime/   
In this website the white dot is the mouse pointer follower effect
 the mouse pointer follower gives look and feel to the user, and also the style and animation of the cursor is minimalistic
@VidhiBhatt01

**Comment by VidhiBhatt01** [comment]
Honestly, I dint like the mouse pointer effect. I feel the current one is better. Any other effect you can do?

**Comment by VinayBagalakoti** [comment]
@VidhiBhatt01 please assign this to me

**Comment by VidhiBhatt01** [comment]
> @VidhiBhatt01 please assign this to me

You din't answer the question asked earlier.

**Comment by VinayBagalakoti** [comment]
![image](https://github.com/Codess-Cafe/Codess-Website/assets/115929590/5d5f1b6f-0162-4d8e-8474-6d1d14626900)
i can add sliding  animation for the text in this image
@VidhiBhatt01

**Comment by VidhiBhatt01** [comment]
We already have a PR which adds Animation to this text

**Comment by cat-macedo** [comment]
Hi, if no one has solved this issue yet, I think I can make the scrolling smooth and add mouse pointer follower effect. 
Here's a video for the mouse pointer effect: [https://www.youtube.com/watch?v=EoKZ2iuJYuU](url)
