### ISSUE TITLE
Betterment of 'Numbers Speak Louder' Section

### ISSUE THREAD

**Issue by RuchNas-Pottah** [Codess-Cafe/Codess-Website#26]
'Offers and Scholarships Bagged' instead of 'Offers and scholarships bagged' 
'Average CTC' instead of 'Avg CTC'
@VidhiBhatt01 please assign this issue to me, if approved!

**Comment by VidhiBhatt01** [comment]
Assigned, please finish it within 24 hours..

**Comment by RuchNas-Pottah** [comment]
> Assigned, please finish it within 24 hours..

Made the necessary changes, Ma'am.
I will be glad to have it approved by You.
