### ISSUE TITLE
A "Star Achievers of the Month" section in Homepage

### ISSUE THREAD

**Issue by coderbysoul** [Codess-Cafe/Codess-Website#27]
Just as the Codess. Cafe Linkedin page shares Star Achievers of each month, how about implementing that idea and showcasing it in the website as well. This will give wider recognition and motivation to the achievers, and inspire other girls to follow their footsteps as well.

**Comment by VidhiBhatt01** [comment]
@coderbysoul,  this would require a lot of operational effort and we do not have the bandwidth for it at the moment. Thanks for coming up with the idea though!
