### ISSUE TITLE
Stylize the texts in the hero section of the Homepage

### ISSUE THREAD

**Issue by coderbysoul** [Codess-Cafe/Codess-Website#28]
![image](https://github.com/Codess-Cafe/Codess-Website/assets/96008596/33b39a70-d3d0-4c3a-a86c-60ddc31fffbe)
 I want to use some text animations here

**Comment by VidhiBhatt01** [comment]
Assigned, please finish it within 24 hours..

**Comment by DeepRahangdale** [comment]
You can assign me this if not finished yet

**Comment by NishantKuthe** [comment]
can you assign this to me
