### ISSUE TITLE
Style the cards of team members

### ISSUE THREAD

**Issue by ishanchaskar** [Codess-Cafe/Codess-Website#31]
the card style is too basic i would like to work on it to make it better and aesthetic can you please assign this task to me @VidhiBhatt01

**Comment by VidhiBhatt01** [comment]
This issue is actually on the priority list. We already have #2 and #4 similar to this. Let's wait and see the output after these two issues are resolved. If the design is still poor and you feel you can enhance it, please do reopen this issue!
