### ISSUE TITLE
Hacktoberfest 2023 🎉 : Revise Team Member Information

### ISSUE THREAD

**Issue by joeyouss** [Codess-Cafe/Codess-Website#4]
Issue Description:

The existing information in the "Meet the Team" section needs to be updated. The content should accurately reflect the current team structure and roles within the organization. 

Update the information according to the info below
[1] Remove the Editor in Chief Card.

[2] Update description: Shriya Chabbra -
Founder
SDE: Microsoft | CSE, IGDTUW

[3] Organizational Lead - Vidhi Bhatt
Update photo: Use current profile picture on [LinkedIn](https://www.linkedin.com/in/vidhibhatt01/)
Update description: 
Organizational Lead: India
SDE Intern: Amazon | CSE, GTU

[4] Update description: Sumee Adhikari -
Organization Lead : Nepal
QA Engineer : Clicked

[5] Update description: Hira Farooq - 
Organization Lead : Pakistan
APM: Vyro

[6] Update description: Subhanshi Rawat
Organization Lead : Qatar
SDE : ION
Update photo: Use current profile picture on [LinkedIn](https://www.linkedin.com/in/subhanshi-rawat/)

![image](https://github.com/Codess-Cafe/Codess-Website/assets/83345228/caac62d5-f75a-405a-b1c2-76448770fb13)

**Comment by mohitparmar1** [comment]
i would like to work on this issue!

**Comment by therefat** [comment]
assign me

**Comment by Tooba-Amjad** [comment]
You can assign this issue to me I have almost 50% done with it

**Comment by Tanulr** [comment]
Hey, I'd like to be assigned to this. I can necessarily complete this within 24 hours.

**Comment by VidhiBhatt01** [comment]
Assigned on first come first serve basis to @mohitparmar1 . If not completed within 48 hours, will assign it to someone else

**Comment by tash04** [comment]
Hey @VidhiBhatt01  , I would like to contribute to this.

**Comment by Tooba-Amjad** [comment]
Ca you plz explain 
 **Remove the Editor in Chief Card.**
 Basicllly we have to update the vidhi bhatt info from **Editor-in-cheif** to **Organizational Lead - Vidhi Bhatt** 
 Right?

**Comment by Tooba-Amjad** [comment]
@VidhiBhatt01 Have a look 


https://github.com/Codess-Cafe/Codess-Website/assets/106931048/d17b5948-e09c-43ca-8c36-8db7769c976f


Ok or need amendmentS?

**Comment by Tooba-Amjad** [comment]
I will fix your image issue in issue #2

**Comment by Tooba-Amjad** [comment]
I am sorry but that's not the way 
You asked me to that 
I spend one of my day to do this 
And now you have merged someone's else PR 
That's not fair

**Comment by Tooba-Amjad** [comment]
@VidhiBhatt01 I am sorry but that's not the way 
You asked me to that 
I spend one of my day to do this 
And now you have merged someone's else PR 
That's not fair

**Comment by VidhiBhatt01** [comment]
@Tooba-Amjad, I understand you concern. But yours required some changes. His was a valid one. Since I explicitly asked you to work on it and to be fair, I added the "hacktoberfest-accepted" label and gave approval too even though it required changes. Since that PR has both the above things, it would be considered as a valid hacktoberfest PR. PLease lmk it this one is not fetched on your hacktoberfest dashboard even after next 7 days.


Reference: https://hacktoberfest.com/participation/

**Comment by Tooba-Amjad** [comment]
@VidhiBhatt01 
![Screenshot (207)](https://github.com/Codess-Cafe/Codess-Website/assets/106931048/bb038dac-3287-40e5-8198-a91cb5d08db0)

**Comment by VidhiBhatt01** [comment]
It takes 7 days to get reflected

**Comment by VidhiBhatt01** [comment]
Do one thing reopen that PR. Push a new commit to that PR. I will merge it.

In the bew commit, remove the files that are already added in your last commit to avoid merge conflicts and make some minor change in either of the file

**Comment by Tooba-Amjad** [comment]
ok
