### ISSUE TITLE
[BUG] In the footer section, the copyright year should be dynamically generated instead of being statically hardcoded.

### ISSUE THREAD

**Issue by gauravsingh1281** [Codess-Cafe/Codess-Website#44]
<img width="960" alt="Screenshot 2023-10-20 003233" src="https://github.com/Codess-Cafe/Codess-Website/assets/85905403/c3006107-fbaf-4846-b036-511e3d0b2c52">

**Comment by gauravsingh1281** [comment]
@Ruchip16 @VidhiBhatt01 Right now, the copyright year is written manually, which means someone has to change it whenever a new year begins. However, with just a few lines of code in JavaScript, we can make it automatic. This means that the copyright year will always be up-to-date without anyone having to change it manually. For example, if the current year is 2023, the copyright section will show 2023. And when the year changes to 2024, the copyright section will automatically update to 2024.

**Comment by gauravsingh1281** [comment]
@Ruchip16 @VidhiBhatt01 Please assign this issue to me under hacktoberfest label.

**Comment by Ruchip16** [comment]
sure, go ahead!

**Comment by Blink29** [comment]
can you please assign me the issue

**Comment by VidhiBhatt01** [comment]
@gauravsingh1281, please complete this issue soon

**Comment by Blink29** [comment]
i have solved the issue please assign it to me
<img width="1250" alt="Screenshot 2023-10-21 at 4 55 31 PM" src="https://github.com/Codess-Cafe/Codess-Website/assets/115066832/03f54bda-bea0-4abd-8e72-38cf2ccb75f2">

**Comment by Blink29** [comment]
@Ruchip16  @VidhiBhatt01

**Comment by VidhiBhatt01** [comment]
Will assign it to you @Blink29 if @gauravsingh1281 does not finish it within next 48 hours

**Comment by gauravsingh1281** [comment]
@VidhiBhatt01 Sorry for being late. I will do this today actually I was busy with my College exam now I'm free.

**Comment by Blink29** [comment]
@VidhiBhatt01 please assign it to me as it had already been 2 days
