### ISSUE TITLE
Create a "Send Message" Form for Contact Us section

### ISSUE THREAD

**Issue by coderbysoul** [Codess-Cafe/Codess-Website#47]
I want to create a form for Contact Us section, where visitors to the website can type their messages and send it to the authorities. Here is a demo of that :
![image](https://github.com/Codess-Cafe/Codess-Website/assets/96008596/61c0bb05-6230-4c76-b259-078853b487ea)
I will also stylise the form and send button a bit

**Comment by Ruchip16** [comment]
sure, go ahead and submit the PR for same within 48 hours

**Comment by VidhiBhatt01** [comment]
@coderbysoul How would the form data reach the org? What's the backend architecture for this? you should cover these points while submitting the issue.

PS: We already have a contact us support id. I don't see the need for this added feature. Please finish the issues that are already assigned. Once they are resolved, you can create/propose new ones
