### ISSUE TITLE
Fix : Mentorship matters heading

### ISSUE THREAD

**Issue by Jyoti040** [Codess-Cafe/Codess-Website#49]
In the mobile view , the heading " Mentorship matters " is aligned to the extreme left with no space and makes ui of the screen a little poor. I want to fix this 
Here is the screenshot of issue I'm talking about :- 
![Screenshot_20231020_230654_WhatsApp](https://github.com/Codess-Cafe/Codess-Website/assets/133634700/2983e6c0-dbcf-4f20-a1ce-325907f83115)

**Comment by Ruchip16** [comment]
sure, go ahead and submit the PR for the same within 48 hours
