### ISSUE TITLE
Hacktoberfest 2023 🎉 : Add Horizontal Spacing between Section Heading and Testimonial Cards

### ISSUE THREAD

**Issue by joeyouss** [Codess-Cafe/Codess-Website#5]
Issue Description:
In the testimonial section, there is a need to improve the layout for better readability and visual appeal. Currently, there is insufficient horizontal spacing between the section heading and the testimonial cards, causing a cramped appearance.

To address this issue, developers should adjust the CSS styles or layout to introduce appropriate horizontal spacing. This adjustment will provide a clear visual distinction between the section heading and the testimonial cards, ensuring a more organized and pleasing display.

![image](https://github.com/Codess-Cafe/Codess-Website/assets/83345228/0babec03-695c-4df4-850e-f1570aedea24)

**Comment by aryankshl** [comment]
hey @joeyouss can you assign this to me?

**Comment by Albert-2** [comment]
hey @joeyouss ..
I would love to contribute to your project can you please assign me this issue...
THANK YOU....!!:)

**Comment by Reene-Simon** [comment]
@joeyouss @VidhiBhatt01 could u please assign this issue to me? I would love to work on it as one of my initial issues. I'm proficient in CSS and believe that I can fix this issue.

**Comment by mannu-bishnoi** [comment]
@VidhiBhatt01 could you please assign this task to me?

**Comment by VidhiBhatt01** [comment]
Assigned on first come first serve basis to @aryankshl. If not completed within 48 hours, will assign it to someone else

**Comment by Ruchip16** [comment]
closing the issue as PR has been merged
