### ISSUE TITLE
The FAQ's section should expand on clicking anywhere is the card.

### ISSUE THREAD

**Issue by gaurovgiri** [Codess-Cafe/Codess-Website#51]
![image](https://github.com/Codess-Cafe/Codess-Website/assets/64427471/943d48c9-9106-4196-af5c-6da4a3f26ff5)

The existing design of the FAQ card only allows expansion when users click on the text inside the card, which might not offer the most user-friendly experience. I am eager to contribute to this project by enhancing the design to make it more user-friendly.

**Comment by Blink29** [comment]
can you please assign me the issue and add the hacktoberfest label please

**Comment by Ruchip16** [comment]
@gaurovgiri go ahead and submit the PR for the same within 48 hours
