### ISSUE TITLE
Chapter led by person name updation

### ISSUE THREAD

**Issue by coderbysoul** [Codess-Cafe/Codess-Website#58]
I recently came across the "Meet the Team" enhancement issue which states that Vidhi Bhatt is the India Chapter lead now. So if I am not wrong, the same change should also be updated in the upcoming chapters card.
![image](https://github.com/Codess-Cafe/Codess-Website/assets/96008596/98c130e0-a44d-4726-acf9-7fdc9110a985)
Should I do the change?

**Comment by VidhiBhatt01** [comment]
It's already updated in other PR. Latest version is yet to be deployed
