### ISSUE TITLE
BUG - [WEBSITE IS NOT RESPONSIVE]

### ISSUE THREAD

**Issue by AryanShriv** [Codess-Cafe/Codess-Website#59]
![image](https://github.com/Codess-Cafe/Codess-Website/assets/98581701/6c8270e2-6b69-4c76-9960-5dae3960e876)

Due to some libraries used, it is not responsive for mobile devices

**Comment by AryanShriv** [comment]
@VidhiBhatt01 
Please assign this to me.

**Comment by VidhiBhatt01** [comment]
Assigned, please complete within 48 hours
