### ISSUE TITLE
Hacktoberfest 2023 🎉 : Improve Alignment of Codess.cafe Logo

### ISSUE THREAD

**Issue by joeyouss** [Codess-Cafe/Codess-Website#6]
Issue Description
While the Codess.cafe logo is displaying on the website, there is an alignment issue that affects its overall visual appeal. The goal of this issue is to enhance the alignment of the logo, ensuring it is perfectly centered and aligned with other elements on the webpage. Developers should review the existing CSS styles and layout to identify the source of misalignment.
Adjustments in CSS properties like margin, padding, or positioning may be necessary to achieve the desired alignment.

![image](https://github.com/Codess-Cafe/Codess-Website/assets/83345228/b2a8f2d4-81cf-42b0-9a83-4a9362e9c5c5)

**Comment by Aniumbott** [comment]
can I work on this?

**Comment by mohitparmar1** [comment]
before :
![Screenshot (191)](https://github.com/Codess-Cafe/Codess-Website/assets/100152343/9f9d173f-ff21-4ab7-a7b8-a0164e8bccea)
after:
![Screenshot (190)](https://github.com/Codess-Cafe/Codess-Website/assets/100152343/e87f9dd8-94d9-40fb-9892-bc3ba8fb4f64)

**Comment by Reene-Simon** [comment]
@joeyouss @VidhiBhatt01 Could u please assign this issue to me? I would like to work on it as one of my initial issues?

**Comment by mannu-bishnoi** [comment]
@joeyouss  @VidhiBhatt01  could you please assign this issue to me?

**Comment by cyberdad68** [comment]
i would like to work on this issue,Could you assign me this.

**Comment by VidhiBhatt01** [comment]
Assigned on first come first serve basis to @Aniumbott . If not completed within 48 hours, will assign it to someone else

**Comment by VidhiBhatt01** [comment]
@cyberdad68 @mannu-bishnoi , assigned it to you both. Will accept the PR of whosoever raises a valid one first

**Comment by Akshada-26** [comment]
Please assign this issue to me

**Comment by Reene-Simon** [comment]
@VidhiBhatt01 could u please assign this issue to me as the assignees haven't responded in quite some time?
