### ISSUE TITLE
Stylise the Mentorship Matters Section

### ISSUE THREAD

**Issue by coderbysoul** [Codess-Cafe/Codess-Website#61]
I want to add an animated effect to the Mentorship Matters(About Us)  section. Since this section is right after the hero section , it plays an important aspect of the website. In order to make this section visually appealing, I want to add some basic but sober animations to the image and text.
![image](https://github.com/Codess-Cafe/Codess-Website/assets/96008596/f3a6e770-10a9-43a9-a54c-4daf5ef11ced)

PS: I am working on this thing in my system and this is the demo-->

https://github.com/Codess-Cafe/Codess-Website/assets/96008596/5b5be2f0-5734-43e8-a08e-f3c75fec5d63

Can I work on this issue?

**Comment by VidhiBhatt01** [comment]
Sure, go on
