### ISSUE TITLE
Enhancing the FAQ Section for Improved User Experience

### ISSUE THREAD

**Issue by saurav1207** [Codess-Cafe/Codess-Website#67]
The current FAQ section on the website is functional, but there are opportunities to make it more visually appealing and efficient in terms of space utilization.

 
![faq](https://github.com/Codess-Cafe/Codess-Website/assets/93045673/ba11ff5b-2e67-4d64-ad33-84780040176e)

I would like to work on it, so please consider assigning this issue to me. I am eager to start working on the suggested improvements and look forward to contributing to the enhancement of the FAQ section.

**Comment by VidhiBhatt01** [comment]
This section is already enhanced. The deployed website does not have latest changes

**Comment by saurav1207** [comment]
Ma'am, there is a need for improvement in the FAQ section. The answers
don't align with the questions, and the social media icons overlap the FAQ.
Additionally, the FAQ answers only open when we click on the question
itself. I can fix these issues and make further improvements. For instance,
currently, a simple question and answer cover the entire screen. I would
like to make better use of the space by dividing the FAQ into two halves.
Can I open a new issue to address these improvements?
