### ISSUE TITLE
Improving the Navbar

### ISSUE THREAD

**Issue by gayatriagarwal19** [Codess-Cafe/Codess-Website#69]
I would like to  improve the navbar and make it fixed for easy navigation. I've attached the screenshots of how I am thinking about improving it, if you like it please assign this issue to me.  @VidhiBhatt01 

Before:
![Codess Cafe _ Pro-bono mentorship program for women in tech - Google Chrome 21-10-2023 23_32_39](https://github.com/Codess-Cafe/Codess-Website/assets/98116507/38c1b3d9-42c6-4ceb-b7b9-bf98829b6937)

After:
![Codess Cafe _ Pro-bono mentorship program for women in tech - Google Chrome 21-10-2023 23_28_03](https://github.com/Codess-Cafe/Codess-Website/assets/98116507/d945be99-343c-44fc-a154-0af2049c9c61)
 
![Codess Cafe _ Pro-bono mentorship program for women in tech - Google Chrome 21-10-2023 23_28_12](https://github.com/Codess-Cafe/Codess-Website/assets/98116507/06d1e8d4-8480-4cac-9a40-daa353c05f03)

If you want any changes in my idea, please do suggest!

**Comment by VidhiBhatt01** [comment]
I think the current one is better

**Comment by gayatriagarwal19** [comment]
Okay no problem
