### ISSUE TITLE
TEAM SECTION IS DISTORTED

### ISSUE THREAD

**Issue by AryanShriv** [Codess-Cafe/Codess-Website#72]
![image](https://github.com/Codess-Cafe/Codess-Website/assets/98581701/0ccbad3f-ee55-473b-9585-5986a6b39b9e)

**Comment by AryanShriv** [comment]
I guess CSS classes are overlapped and are causing distortion.

**Comment by VidhiBhatt01** [comment]
It looks fine on my local, can you pull and recheck?

**Comment by AryanShriv** [comment]
It looks fine now in desktop view.

![image](https://github.com/Codess-Cafe/Codess-Website/assets/98581701/5daafb29-a01d-4a5e-adfe-9067e7e8575d)
But in responsive, changes can be done if it feels right

**Comment by VidhiBhatt01** [comment]
Sure, fix responsiveness

**Comment by AryanShriv** [comment]
Sure @VidhiBhatt01

**Comment by VidhiBhatt01** [comment]
Is this completed?? If yes, please close the issue

**Comment by AryanShriv** [comment]
Yes Vidhi, it was completed and successfully merged.

Thank you
