### ISSUE TITLE
Hover effect for navbar links

### ISSUE THREAD

**Issue by Varad0014** [Codess-Cafe/Codess-Website#74]
Hey! I've got a few suggestions for hover effects on the navbar links:
![horizontal](https://github.com/Codess-Cafe/Codess-Website/assets/77493105/dd3e4b22-988b-41a6-a068-30052fb93579)
![vertical](https://github.com/Codess-Cafe/Codess-Website/assets/77493105/e367b05d-6c36-4dd8-a772-d9612279d8ad)
![horizontal-vertical](https://github.com/Codess-Cafe/Codess-Website/assets/77493105/ad8607b5-a728-48df-a14b-37f360c2445a)

Let me know if you're interested in any of these, and I can incorporate them into the website.

**Comment by VidhiBhatt01** [comment]
Please go on with first one

**Comment by atul120212** [comment]
can you please assign this to me?
