### ISSUE TITLE
Stylize the "Numbers Speak Louder" Section

### ISSUE THREAD

**Issue by Reene-Simon** [Codess-Cafe/Codess-Website#77]
The section currently looks like this-->
![Numbers Old](https://github.com/Codess-Cafe/Codess-Website/assets/112744886/a47f1668-854c-48db-a72c-fbb1c1193419)
I want to stylize this section so that it blends more with the original theme of the website.
I have worked on this in my local in order to give a demo. Here is it:-->
![Number Issue](https://github.com/Codess-Cafe/Codess-Website/assets/112744886/9e705a76-e2f6-44a3-9462-b750d0c9e327)
If you have any other suggestions as regards to the color or anything else, I would be open to it.

Can I work on this issue?

**Comment by VidhiBhatt01** [comment]
the current one is better ig

**Comment by Reene-Simon** [comment]
Yeah no worries! My idea stemmed from the issue that the title and the stats are of the same color and it somehow looks quite bland. Maybe we can do something else to spice up the section?
