### ISSUE TITLE
Add hover effect to the images and enable the smooth property for scroll down

### ISSUE THREAD

**Issue by siddhant2002** [Codess-Cafe/Codess-Website#80]
https://github.com/Codess-Cafe/Codess-Website/assets/78552027/8e9fc82f-1838-4032-889f-baefa3f59cf5

**Comment by siddhant2002** [comment]
Hey @VidhiBhatt01, I would like to make the above changes. Thanks.

**Comment by Ruchip16** [comment]
sure, go ahead and submit the pull request within 48 hours

**Comment by siddhant2002** [comment]
Raised pr #83 . @Ruchip16 Please review. Thanks.
