### ISSUE TITLE
 Request to Manage FAQ Section Improvements

### ISSUE THREAD

**Issue by saurav1207** [Codess-Cafe/Codess-Website#82]
Hello @Ruchip16 Ma'am,

I'd like to take on the task of enhancing the FAQ section. Specifically, I'd align answers better with questions and divide the FAQ into two halves to optimize space usage, making it more aesthetically pleasing to users.

Please find attached a visual representation of how the changes will look. Can you please assign this task to me?

Thank you!

**Before:**
![faqq3](https://github.com/Codess-Cafe/Codess-Website/assets/93045673/26e12c2b-32b6-438d-bcfe-62efbffc5b76)

**After:**
![faaqq (2)](https://github.com/Codess-Cafe/Codess-Website/assets/93045673/5588a203-3fe6-4940-aa0f-9ae01bd17b7c)

**Comment by Ruchip16** [comment]
sure, go ahead and submit the PR within 48 hours
