### ISSUE TITLE
Missing Information

### ISSUE THREAD

**Issue by Reene-Simon** [Codess-Cafe/Codess-Website#85]
In the "Meet the Team" section, the card for the UAE chapter lead is missing. It is there on the original website and is missing in the GitHub Repo. I would like to rectify this error and add the missing card with the relevant information. 
Can I work on this issue?

**Comment by VidhiBhatt01** [comment]
sure

**Comment by Reene-Simon** [comment]
The PR for this issue has been merged hence closed the issue.
