### ISSUE TITLE
Fix : transition of social icons

### ISSUE THREAD

**Issue by Srishdwi02** [Codess-Cafe/Codess-Website#86]
When the social icons are unhovered, , the transition of social icons to original state is not smooth.
expected:

https://github.com/Codess-Cafe/Codess-Website/assets/138107242/c6bf80e3-7b90-4502-8e0f-9b233752de96

right now actual:

https://github.com/Codess-Cafe/Codess-Website/assets/138107242/071e267e-8822-4532-86f0-a74ad090dcd9

**Comment by Srishdwi02** [comment]
I can fix this , please assign this to me.

**Comment by VidhiBhatt01** [comment]
Am sorry, but can you elaborate on what's the difference between two?

**Comment by Srishdwi02** [comment]
When a user hovers over the icons, triggering a transition, and then unhovers, the subsequent return to their original state lacks smoothness

Moreover if user unhovers on the icon during the transition, the icons abruptly return to the original state without smooth transition
