### ISSUE TITLE
Social media Icons must be more prominent in Footer section 

### ISSUE THREAD

**Issue by Tooba-Amjad** [Codess-Cafe/Codess-Website#93]
@VidhiBhatt01 Look
**How it looks now!**

![Screenshot (238)](https://github.com/Codess-Cafe/Codess-Website/assets/106931048/fbeea6d2-4222-47f6-a3bf-e63efee683df)

**How it'll**

https://github.com/Codess-Cafe/Codess-Website/assets/106931048/2c2f6b01-82c9-470f-928a-f4612e4e8ff8

**Comment by VidhiBhatt01** [comment]
@Tooba-Amjad are you available for a 10min  google meet?

**Comment by Tooba-Amjad** [comment]
Yes

**Comment by VidhiBhatt01** [comment]
please join: https://meet.google.com/ogg-hsbb-uvw at 8:15 pm

**Comment by Tooba-Amjad** [comment]
Ok

**Comment by VidhiBhatt01** [comment]
Create new issues and raise new PRs as discussed in the meet... 

Closing this one as its no longer relevant
