### ISSUE TITLE
[feat]: Add a Preloader to the website

### ISSUE THREAD

**Issue by purnasth** [Codess-Cafe/Codess-Website#95]
# Issue Title: Add Preloader

## Issue Description
I propose adding a preloader to improve the user experience while the website is loading. A preloader provides visual feedback to users that the page is loading, enhancing the overall aesthetics of the website.

## Additional Information (if available)
If there are specific design preferences for the preloader or any guidelines for contributing to the repository, please provide them to ensure it aligns with the project's goals.

I am eager to contribute this enhancement to the project and look forward to your guidance and feedback.

**Comment by VidhiBhatt01** [comment]
Hey, please wait for a while. We have some major changes being made to the website. once they are done, I will assign it to you.

Till then can help me understand your proposal better by providing some sample video/img ?

**Comment by purnasth** [comment]
https://github.com/Codess-Cafe/Codess-Website/assets/107195487/8dd16534-29e4-4ef5-a6b5-b6df31789165


https://github.com/Codess-Cafe/Codess-Website/assets/107195487/01e3385f-5417-415d-b9af-6c91afa98389


https://github.com/Codess-Cafe/Codess-Website/assets/107195487/7586b07e-b95c-4a78-8942-08b2d327d893

**Comment by VidhiBhatt01** [comment]
Am sorry but I din't like either of the loaders.. You can check out other issues...
